[[redirects]]
  from = "/bai-viet/10-giao-dien-theme-dep-xuat-sac-cho-sublime-text-3"
  to = "/bai-viet/sublime-text-3-themes"

[[redirects]]
  from = "/bai-viet/nhung-plugins-khong-the-thieu-cho-vs-code/"
  to = "/bai-viet/vscode-must-have-plugins"

[[redirects]]
  from = "/bai-viet/tai-lieu-javascript-tu-co-ban-den-nang-cao"
  to = "/bai-viet/free-javascript-books-beginner-advanced"

[[redirects]]
  from = "/bai-viet/learn-typescript-together-basics/index.html"
  to = "/learn-typescript-together/basic-types"

[[redirects]]
  from = "/bai-viet/learn-typescript-together-basics"
  to = "/learn-typescript-together/basic-types"

[[redirects]]
  from = "/bai-viet/newsletter-2022-week-38"
  to = "/ban-tin/2022-week-38"

[[redirects]]
  from = "/bai-viet/newsletter-2022-week-37"
  to = "/ban-tin/2022-week-37"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
