[[redirects]]
  from = "/bai-viet/10-giao-dien-theme-dep-xuat-sac-cho-sublime-text-3"
  to = "/bai-viet/sublime-text-3-themes"

[[redirects]]
  from = "/bai-viet/nhung-plugins-khong-the-thieu-cho-vs-code/"
  to = "/bai-viet/vscode-must-have-plugins"

[[redirects]]
  from = "/bai-viet/tai-lieu-javascript-tu-co-ban-den-nang-cao"
  to = "/bai-viet/free-javascript-books-beginner-advanced"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
